#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

# Load GH_TOKEN (and other vars) from .env if present.
# electron-builder reads GH_TOKEN to embed it in app-update.yml for private repo auto-update.
if [[ -f .env ]]; then
  set -a
  source .env
  set +a
fi

PROFILE="${NOTARY_PROFILE:-otto-notary}"
OUT_DIR="release-mac"
VERSION="${npm_package_version:-$(node -p "require('./package.json').version")}"

if [[ -z "${GH_TOKEN:-}" ]]; then
  echo "Warning: GH_TOKEN is not set. Auto-update from the private repo will not work."
  echo "Set GH_TOKEN in .env or export it before running this script."
fi

# Expected artifact names (set by electron-builder artifactName in package.json)
ARM_DMG="${OUT_DIR}/otto-tracker-mac-arm64.dmg"
ARM_ZIP="${OUT_DIR}/otto-tracker-mac-arm64.zip"
X64_DMG="${OUT_DIR}/otto-tracker-mac-x64.dmg"
X64_ZIP="${OUT_DIR}/otto-tracker-mac-x64.zip"
# electron-updater manifest (generated by electron-builder with publish config)
LATEST_MAC_YML="${OUT_DIR}/latest-mac.yml"

echo "=== Building web + server bundle ==="
npm run build

rm -rf "${OUT_DIR}"

# Write the auto-update token into desktop/lib/update-token.js so it gets
# shipped inside the packaged app.  electron-updater needs it at runtime to
# authenticate against the private GitHub repo.
echo "// Auto-generated at build time. DO NOT commit." > desktop/lib/update-token.js
echo "export const UPDATE_TOKEN = \"${GH_TOKEN:-}\";" >> desktop/lib/update-token.js

verify_app_signature() {
  local arch="$1"
  local app_path="$2"

  echo ""
  echo "=== Verifying ${arch} .app signature ==="

  if [[ ! -d "${app_path}" ]]; then
    echo "App bundle not found: ${app_path}"
    return 1
  fi

  echo "Verifying code signature on ${app_path}..."
  local sign_info
  sign_info="$(codesign -dv --verbose=4 "${app_path}" 2>&1 || true)"

  if [[ "${sign_info}" == *"Signature=adhoc"* ]]; then
    echo "${sign_info}"
    echo "App is ad-hoc signed. Fix Developer ID signing before notarizing."
    return 1
  fi

  if [[ "${sign_info}" == *"TeamIdentifier=not set"* ]]; then
    echo "${sign_info}"
    echo "TeamIdentifier is not set. Developer ID identity was not applied."
    return 1
  fi

  codesign --verify --deep --strict --verbose=2 "${app_path}"
}

notarize_artifact() {
  local label="$1"
  local artifact_path="$2"

  echo ""
  echo "=== Notarizing ${label} ==="

  if [[ ! -f "${artifact_path}" ]]; then
    echo "Artifact not found: ${artifact_path}"
    return 1
  fi

  echo "Submitting ${artifact_path} to Apple notary service (profile: ${PROFILE})..."
  xcrun notarytool submit "${artifact_path}" -p "${PROFILE}" --wait

  echo "Stapling notarization ticket..."
  xcrun stapler staple "${artifact_path}"
  xcrun stapler validate "${artifact_path}"

  echo "Done: ${artifact_path}"
}

# Build both architectures in a single invocation so electron-builder produces
# a single latest-mac.yml that references both arm64 and x64 ZIPs.  This is
# required for electron-updater to serve the correct arch to each machine.
echo ""
echo "=== Building macOS ARM + x64 ==="
npx electron-builder --mac --arm64 --x64 -c.directories.output="${OUT_DIR}"
ARM_APP="$(find "${OUT_DIR}/mac-arm64" -maxdepth 1 -type d -name "*.app" 2>/dev/null | head -n 1 || true)"
X64_APP="$(find "${OUT_DIR}/mac" -maxdepth 1 -type d -name "*.app" 2>/dev/null | head -n 1 || true)"

verify_app_signature "arm64" "${ARM_APP}"
verify_app_signature "x64"   "${X64_APP}"

# Notarize DMGs so Gatekeeper shows the verified-developer checkmark when users
# mount them.  Do NOT notarize/staple the ZIPs — stapling modifies the file,
# which would invalidate the sha512 hashes in latest-mac.yml and break
# electron-updater's integrity check.  The .app inside the ZIP is already
# notarized by electron-builder's `notarize: true` at build time, so macOS
# will accept it when the auto-updater extracts it.
notarize_artifact "arm64 DMG" "${ARM_DMG}"
notarize_artifact "x64 DMG"   "${X64_DMG}"

echo ""
echo "Running Gatekeeper assessment on DMGs..."
spctl -a -vv -t open "${ARM_DMG}"
spctl -a -vv -t open "${X64_DMG}"

echo ""
echo "=== Release complete ==="
echo "  ARM64 DMG: ${ARM_DMG}"
echo "  ARM64 ZIP: ${ARM_ZIP}"
echo "  x64   DMG: ${X64_DMG}"
echo "  x64   ZIP: ${X64_ZIP}"
echo "  Update manifest: ${LATEST_MAC_YML}"
echo ""
echo "To upload to GitHub Release:"
echo "  npm run release:upload"
