const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("otto", {
  getConfig: () => ipcRenderer.invoke("otto:config:get"),
  saveConfig: (config) => ipcRenderer.invoke("otto:config:set", config),
  testConnection: (payload) => ipcRenderer.invoke("otto:connection:test", payload),
  outboxGet: () => ipcRenderer.invoke("otto:outbox:get"),
  outboxReplace: (items) => ipcRenderer.invoke("otto:outbox:replace", items),
  outboxClear: () => ipcRenderer.invoke("otto:outbox:clear"),
  showHostAddresses: () => ipcRenderer.invoke("otto:hostAddresses:show"),
  getHostInfo: () => ipcRenderer.invoke("otto:hostInfo:get"),
  discoverHosts: (payload) => ipcRenderer.invoke("otto:hosts:discover", payload),
  setWindowMinWidth: (width) => ipcRenderer.invoke("otto:window:set-min-width", width),
  openSmsDraft: (payload) => ipcRenderer.invoke("otto:sms:draft:open", payload),
  portalFindHost: (payload) => ipcRenderer.invoke("otto:portal:find-host", payload),
  portalDesktopAuth: (payload) => ipcRenderer.invoke("otto:portal:desktop-auth", payload),
  validateInviteCode: (payload) => ipcRenderer.invoke("otto:portal:validate-invite-code", payload),
  clientRegister: (payload) => ipcRenderer.invoke("otto:portal:client-register", payload),
  setupBootstrap: (payload) => ipcRenderer.invoke("otto:setup:bootstrap", payload),
  setupPickSnapshot: () => ipcRenderer.invoke("otto:setup:pick-snapshot"),
  setupImportSnapshot: (payload) => ipcRenderer.invoke("otto:setup:import-snapshot", payload),
  setupComplete: () => ipcRenderer.invoke("otto:setup:complete"),
  showDiagnostics: () => ipcRenderer.invoke("otto:diagnostics:show"),
  exportSupportBundle: () => ipcRenderer.invoke("otto:supportBundle:export"),
});
